[package]
name = "Rusty_Dungeon"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14", features = ["tokio"] }
serde_json = "1.0.149"
tokio = { version = "1", features = ["full"] }
