services:
  db:
    image: postgres:18
    volumes:
      - "/var/rusty-dungeon/db:/var/lib/postgresql"
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=db-1
  api:
    build: .
    ports:
      - "27010:27010"
